#!/bin/bash
#
# UTSensing Air Quality Monitor - Security Hardening Script
#
# This script implements security best practices for your Raspberry Pi
# Run as: sudo bash security-hardening.sh
#
# What this script does:
# 1. Configures SSH hardening (key-only auth, disable root login)
# 2. Installs and configures fail2ban
# 3. Sets up UFW firewall
# 4. Configures automatic security updates
# 5. Sets secure file permissions
#
# IMPORTANT: Before running this script:
# - Ensure you have SSH key-based authentication set up
# - Test that you can log in with your SSH key
# - Have physical access to the Pi in case of lockout
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}UTSensing Security Hardening Script${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Get the actual user (not root)
ACTUAL_USER=${SUDO_USER:-$USER}
if [ "$ACTUAL_USER" = "root" ]; then
    echo -e "${RED}Please run this script with sudo from a regular user account${NC}"
    exit 1
fi

echo -e "${YELLOW}Running as user: $ACTUAL_USER${NC}"
echo ""

#------------------------------------------------------------------------------
# Function: Prompt for confirmation
#------------------------------------------------------------------------------
confirm() {
    read -p "$1 [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        return 0
    else
        return 1
    fi
}

#------------------------------------------------------------------------------
# STEP 1: Update System
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 1/6] Updating system packages...${NC}"
apt update && apt upgrade -y

#------------------------------------------------------------------------------
# STEP 2: Install Security Packages
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 2/6] Installing security packages...${NC}"
apt install -y fail2ban ufw unattended-upgrades apt-listchanges

#------------------------------------------------------------------------------
# STEP 3: Configure SSH Hardening
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 3/6] Configuring SSH hardening...${NC}"

# Backup original SSH config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

# Check if user has SSH keys set up
SSH_KEY_FILE="/home/$ACTUAL_USER/.ssh/authorized_keys"
if [ ! -f "$SSH_KEY_FILE" ] || [ ! -s "$SSH_KEY_FILE" ]; then
    echo -e "${YELLOW}WARNING: No SSH keys found for user $ACTUAL_USER${NC}"
    echo -e "${YELLOW}SSH key authentication is recommended before disabling passwords${NC}"
    echo ""
    echo "To set up SSH keys from your computer:"
    echo "  1. On your computer: ssh-keygen -t ed25519"
    echo "  2. On your computer: ssh-copy-id $ACTUAL_USER@$(hostname -I | awk '{print $1}')"
    echo ""
    if ! confirm "Do you want to continue WITHOUT disabling password authentication?"; then
        echo "Exiting. Please set up SSH keys first."
        exit 1
    fi
    DISABLE_PASSWORDS=false
else
    echo -e "${GREEN}SSH keys found for $ACTUAL_USER${NC}"
    DISABLE_PASSWORDS=true
fi

# Create SSH hardening config
cat > /etc/ssh/sshd_config.d/security-hardening.conf << 'EOF'
# UTSensing Security Hardening Configuration
# Generated by security-hardening.sh

# Disable root login
PermitRootLogin no

# Limit authentication attempts
MaxAuthTries 3

# Disable empty passwords
PermitEmptyPasswords no

# Disable X11 forwarding (not needed for headless server)
X11Forwarding no

# Set login grace time
LoginGraceTime 60

# Disable TCP forwarding (uncomment if not needed)
# AllowTcpForwarding no

# Client alive settings (disconnect idle sessions)
ClientAliveInterval 300
ClientAliveCountMax 2
EOF

if [ "$DISABLE_PASSWORDS" = true ]; then
    echo "PasswordAuthentication no" >> /etc/ssh/sshd_config.d/security-hardening.conf
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config.d/security-hardening.conf
    echo -e "${GREEN}Password authentication disabled (SSH keys only)${NC}"
else
    echo "# PasswordAuthentication no  # Uncomment after setting up SSH keys" >> /etc/ssh/sshd_config.d/security-hardening.conf
    echo -e "${YELLOW}Password authentication left enabled (SSH keys not detected)${NC}"
fi

# Test SSH config before restarting
sshd -t
if [ $? -eq 0 ]; then
    systemctl restart sshd
    echo -e "${GREEN}SSH configuration updated and service restarted${NC}"
else
    echo -e "${RED}SSH configuration test failed! Restoring backup...${NC}"
    rm /etc/ssh/sshd_config.d/security-hardening.conf
    exit 1
fi

#------------------------------------------------------------------------------
# STEP 4: Configure Fail2ban
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 4/6] Configuring fail2ban...${NC}"

# Create local jail configuration
cat > /etc/fail2ban/jail.local << 'EOF'
# UTSensing Fail2ban Configuration
# Protects against brute-force attacks

[DEFAULT]
# Ban duration (10 minutes)
bantime = 10m

# Time window for counting failures
findtime = 10m

# Number of failures before ban
maxretry = 5

# Action to take (ban via iptables)
banaction = iptables-multiport

# Email notifications (uncomment and configure if desired)
# destemail = your@email.com
# sender = fail2ban@raspberrypi
# action = %(action_mwl)s

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 1h
EOF

systemctl enable fail2ban
systemctl restart fail2ban
echo -e "${GREEN}Fail2ban configured and started${NC}"

#------------------------------------------------------------------------------
# STEP 5: Configure UFW Firewall
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 5/6] Configuring UFW firewall...${NC}"

# Reset UFW to defaults
ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH
ufw allow ssh comment 'Allow SSH'

# Allow Home Assistant from local network only
# Detect local network range
LOCAL_IP=$(hostname -I | awk '{print $1}')
LOCAL_NETWORK=$(echo $LOCAL_IP | sed 's/\.[0-9]*$/.0\/24/')

echo -e "${YELLOW}Detected local network: $LOCAL_NETWORK${NC}"
ufw allow from $LOCAL_NETWORK to any port 8123 comment 'Home Assistant local access'

# Allow MQTT local (if using local broker)
ufw allow from $LOCAL_NETWORK to any port 1883 comment 'MQTT local'

# Rate limit SSH to prevent brute-force
ufw limit ssh/tcp comment 'Rate limit SSH'

# Enable UFW
ufw --force enable

echo -e "${GREEN}UFW firewall configured and enabled${NC}"
ufw status verbose

#------------------------------------------------------------------------------
# STEP 6: Configure Automatic Security Updates
#------------------------------------------------------------------------------
echo -e "${GREEN}[Step 6/6] Configuring automatic security updates...${NC}"

# Configure unattended-upgrades
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
// Automatically install security updates
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

// Remove unused kernel packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatic reboot if needed (at 3 AM)
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Keep 7 days of logs
Unattended-Upgrade::SyslogEnable "true";
EOF

# Enable automatic updates
cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

systemctl enable unattended-upgrades
systemctl restart unattended-upgrades
echo -e "${GREEN}Automatic security updates configured${NC}"

#------------------------------------------------------------------------------
# STEP 7: Set Secure File Permissions
#------------------------------------------------------------------------------
echo -e "${GREEN}[Bonus] Setting secure file permissions...${NC}"

# Secure SSH directory
if [ -d "/home/$ACTUAL_USER/.ssh" ]; then
    chmod 700 /home/$ACTUAL_USER/.ssh
    chmod 600 /home/$ACTUAL_USER/.ssh/authorized_keys 2>/dev/null || true
    chmod 600 /home/$ACTUAL_USER/.ssh/id_* 2>/dev/null || true
    chown -R $ACTUAL_USER:$ACTUAL_USER /home/$ACTUAL_USER/.ssh
fi

# Secure data directory if it exists
if [ -d "/home/utsensing/utData" ]; then
    chown -R $ACTUAL_USER:$ACTUAL_USER /home/utsensing
    chmod 750 /home/utsensing/utData
fi

#------------------------------------------------------------------------------
# Summary
#------------------------------------------------------------------------------
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Security Hardening Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Summary of changes:"
echo "  - SSH: Root login disabled, max 3 auth attempts"
if [ "$DISABLE_PASSWORDS" = true ]; then
    echo "  - SSH: Password authentication disabled (key-only)"
else
    echo "  - SSH: Password authentication still enabled (set up SSH keys!)"
fi
echo "  - Fail2ban: Installed and configured (3 failures = 1 hour ban)"
echo "  - UFW Firewall: Enabled with rules:"
echo "      - SSH allowed (rate limited)"
echo "      - Home Assistant (8123) from local network only"
echo "      - All other incoming blocked"
echo "  - Auto-updates: Security updates install automatically"
echo ""
echo -e "${YELLOW}IMPORTANT: Test SSH access in a new terminal before closing this session!${NC}"
echo ""
echo "Next steps:"
echo "  1. Open a NEW terminal and verify you can still SSH in"
echo "  2. Enable 2FA in Home Assistant (Settings > Profile > MFA)"
echo "  3. Consider network segmentation (see SECURITY.md)"
echo ""
echo "To check firewall status: sudo ufw status"
echo "To check fail2ban status: sudo fail2ban-client status sshd"
echo ""
