#!/bin/bash
###############################################################################
# Setup ALSA dsnoop for Shared Audio Capture
# ============================================
# Creates an ALSA dsnoop device so BOTH the dog bark detector (PyAudio)
# and BirdNET (PulseAudio) can read from the loopback capture device
# simultaneously without exclusive access conflicts.
#
# Without dsnoop: Only ONE application can open hw:X,1 at a time.
# With dsnoop:    Multiple applications share the same capture device.
#
# Usage:
#   sudo ./setup_audio_sharing.sh
#
# What this does:
#   1. Detects the ALSA loopback card number
#   2. Creates /etc/asound.conf with dsnoop device definition
#   3. Configures PulseAudio to use the dsnoop device as a source
#   4. Restarts PulseAudio so BirdNET can use it
#
# After running this:
#   - Dog bark detector: Set AUDIO_DEVICE_NAME=dsnoop_loopback (env var)
#   - BirdNET: Uses PulseAudio default source (auto-configured)
#
# Author: Claude Code
# License: MIT
###############################################################################

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}=== Audio Device Sharing Setup ===${NC}"
echo ""

###############################################################################
# Step 1: Detect Loopback Card
###############################################################################

echo -e "${YELLOW}Step 1: Detecting ALSA loopback device...${NC}"

if ! lsmod | grep -q snd_aloop; then
    echo -e "${RED}  ✗ snd-aloop not loaded. Run: sudo modprobe snd-aloop${NC}"
    exit 1
fi

LOOPBACK_CARD=$(arecord -l 2>/dev/null | grep -i "loopback" | head -1 | sed -n 's/card \([0-9]*\):.*/\1/p')

if [ -z "$LOOPBACK_CARD" ]; then
    echo -e "${RED}  ✗ Loopback card not found. Is snd-aloop loaded?${NC}"
    exit 1
fi

echo -e "${GREEN}  ✓ Loopback is card ${LOOPBACK_CARD}${NC}"

###############################################################################
# Step 2: Create ALSA dsnoop Configuration
###############################################################################

echo -e "${YELLOW}Step 2: Creating /etc/asound.conf with dsnoop device...${NC}"

# Back up existing config if it exists
if [ -f /etc/asound.conf ]; then
    cp /etc/asound.conf /etc/asound.conf.bak.$(date +%Y%m%d%H%M%S)
    echo "  Backed up existing /etc/asound.conf"
fi

cat > /etc/asound.conf << ASOUNDEOF
# ALSA dsnoop configuration for shared loopback capture
# Generated by setup_audio_sharing.sh on $(date)
#
# This allows multiple applications (dog bark detector, BirdNET)
# to read from the same ALSA loopback capture device simultaneously.
#
# Device: hw:${LOOPBACK_CARD},1 (capture side of loopback)
# Access via: dsnoop_loopback

# dsnoop device - shared read access to loopback capture
pcm.dsnoop_loopback {
    type dsnoop
    ipc_key 82854
    ipc_perm 0666
    slave {
        pcm "hw:${LOOPBACK_CARD},1"
        rate 16000
        channels 1
        format S16_LE
        period_size 1024
        buffer_size 8192
    }
}

# Convenience alias so "arecord -D loopback" works
pcm.loopback {
    type plug
    slave.pcm "dsnoop_loopback"
}
ASOUNDEOF

echo -e "${GREEN}  ✓ /etc/asound.conf created${NC}"
echo "    dsnoop device: dsnoop_loopback (shared capture from hw:${LOOPBACK_CARD},1)"

###############################################################################
# Step 3: Configure PulseAudio Source
###############################################################################

echo -e "${YELLOW}Step 3: Configuring PulseAudio to use dsnoop device...${NC}"

# Get the user running BirdNET (not root)
AUDIO_USER="${SUDO_USER:-$(logname 2>/dev/null || echo demeter)}"
PULSE_CONFIG="/home/${AUDIO_USER}/.config/pulse"
PULSE_DEFAULT="${PULSE_CONFIG}/default.pa"

mkdir -p "$PULSE_CONFIG"

# Create/update user's PulseAudio config
# Include the system default config first, then add our source
cat > "$PULSE_DEFAULT" << PAEOF
# PulseAudio user config - load dsnoop loopback as default source
# Generated by setup_audio_sharing.sh on $(date)

# Load system defaults
.include /etc/pulse/default.pa

# Load the ALSA dsnoop device as a PulseAudio source
# This uses the shared dsnoop device so other apps (dog bark detector) can also read
load-module module-alsa-source device=dsnoop_loopback source_name=iphone_audio source_properties=device.description="iPhone_Microphone"

# Make it the default source for BirdNET and other PulseAudio apps
set-default-source iphone_audio
PAEOF

chown "${AUDIO_USER}:${AUDIO_USER}" "$PULSE_DEFAULT"
chown "${AUDIO_USER}:${AUDIO_USER}" "$PULSE_CONFIG"

echo -e "${GREEN}  ✓ PulseAudio config updated for user ${AUDIO_USER}${NC}"
echo "    Config: ${PULSE_DEFAULT}"

###############################################################################
# Step 4: Restart PulseAudio
###############################################################################

echo -e "${YELLOW}Step 4: Restarting PulseAudio...${NC}"

# Kill existing PulseAudio (it auto-respawns)
if sudo -u "$AUDIO_USER" pulseaudio --check 2>/dev/null; then
    sudo -u "$AUDIO_USER" pulseaudio --kill 2>/dev/null || true
    sleep 2
fi

# Start PulseAudio
sudo -u "$AUDIO_USER" pulseaudio --start 2>/dev/null || true
sleep 2

# Verify the source exists
if sudo -u "$AUDIO_USER" pactl list sources short 2>/dev/null | grep -q "iphone_audio"; then
    echo -e "${GREEN}  ✓ PulseAudio source 'iphone_audio' is available${NC}"
else
    echo -e "${YELLOW}  ⚠ PulseAudio source not immediately visible - may need a reboot${NC}"
fi

###############################################################################
# Step 5: Test dsnoop Device
###############################################################################

echo -e "${YELLOW}Step 5: Testing dsnoop device...${NC}"

TESTFILE="/tmp/dsnoop_test.wav"
timeout 4 arecord -D dsnoop_loopback -f S16_LE -r 16000 -c 1 -d 2 "$TESTFILE" 2>/dev/null || true

if [ -f "$TESTFILE" ] && [ -s "$TESTFILE" ]; then
    LEVEL=$(python3 -c "
import wave, struct
try:
    w = wave.open('${TESTFILE}', 'r')
    frames = w.readframes(w.getnframes())
    if len(frames) < 4:
        print('empty')
    else:
        samples = [abs(struct.unpack('<h', frames[i:i+2])[0]) for i in range(0, min(len(frames), 64000), 2)]
        peak = max(samples)
        rms = (sum(s*s for s in samples) / len(samples)) ** 0.5
        if peak < 10:
            print('silence')
        else:
            print(f'ok peak={peak} rms={rms:.0f}')
except Exception as e:
    print(f'error: {e}')
" 2>/dev/null)

    case "$LEVEL" in
        ok*)
            echo -e "${GREEN}  ✓ dsnoop audio is working! (${LEVEL})${NC}"
            ;;
        silence)
            echo -e "${YELLOW}  ⚠ dsnoop connected but silent - check iphone-audio-stream${NC}"
            ;;
        *)
            echo -e "${YELLOW}  ⚠ Could not verify audio (${LEVEL})${NC}"
            ;;
    esac
    rm -f "$TESTFILE"
else
    echo -e "${YELLOW}  ⚠ Could not record from dsnoop_loopback${NC}"
    echo "    This may work after restarting services."
fi

###############################################################################
# Summary
###############################################################################

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "Audio sharing configured:"
echo "  ALSA dsnoop device: dsnoop_loopback"
echo "  PulseAudio source:  iphone_audio"
echo ""
echo "Both the dog bark detector and BirdNET can now read audio simultaneously."
echo ""
echo "Next steps:"
echo "  1. Restart the dog bark detector:"
echo "     sudo systemctl restart dog_bark_detector"
echo ""
echo "  2. Restart BirdNET recording:"
echo "     sudo systemctl restart birdnet_recording"
echo ""
echo "  3. Verify both are getting audio:"
echo "     sudo journalctl -u dog_bark_detector -n 20 --no-pager"
echo "     sudo journalctl -u birdnet_recording -n 20 --no-pager"
echo ""
