#!/bin/bash
###############################################################################
# Setup PulseAudio for Shared Audio Capture
# ==========================================
# Configures PulseAudio as the sole consumer of the ALSA loopback capture
# device (hw:X,1). Both the dog bark detector and BirdNET then read from
# PulseAudio, which handles fan-out to multiple readers natively.
#
# Architecture:
#   iPhone (Periscope HD) --> RTSP --> ffmpeg --> hw:X,0 (loopback write)
#                                                    |
#                                               hw:X,1 (loopback read)
#                                                    |
#                                              PulseAudio (sole ALSA reader)
#                                                /        \
#                                     Bark Detector    BirdNET
#
# This eliminates the need for ALSA dsnoop. PulseAudio is the only process
# that opens the raw ALSA device, avoiding subdevice pairing issues.
#
# Usage:  sudo ./setup_audio_sharing.sh
###############################################################################

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}=== PulseAudio Audio Sharing Setup ===${NC}"
echo ""

###############################################################################
# Step 1: Detect Loopback Card
###############################################################################

echo -e "${YELLOW}Step 1: Detecting ALSA loopback device...${NC}"

if ! lsmod | grep -q snd_aloop; then
    echo -e "${RED}  snd-aloop not loaded. Run: sudo modprobe snd-aloop${NC}"
    exit 1
fi

LOOPBACK_CARD=$(arecord -l 2>/dev/null | grep -i "loopback" | head -1 | sed -n 's/card \([0-9]*\):.*/\1/p')

if [ -z "$LOOPBACK_CARD" ]; then
    echo -e "${RED}  Loopback card not found. Is snd-aloop loaded?${NC}"
    exit 1
fi

echo -e "${GREEN}  Loopback is card ${LOOPBACK_CARD}${NC}"

###############################################################################
# Step 2: Configure PulseAudio Source
###############################################################################

echo -e "${YELLOW}Step 2: Configuring PulseAudio...${NC}"

AUDIO_USER="${SUDO_USER:-$(logname 2>/dev/null || echo demeter)}"
PULSE_CONFIG="/home/${AUDIO_USER}/.config/pulse"
PULSE_DEFAULT="${PULSE_CONFIG}/default.pa"

mkdir -p "$PULSE_CONFIG"

# PulseAudio reads directly from the ALSA loopback capture device.
# No dsnoop needed — PulseAudio is the sole ALSA consumer and handles
# fan-out to multiple readers (bark detector + BirdNET) natively.
cat > "$PULSE_DEFAULT" << PAEOF
# PulseAudio config - iPhone loopback audio source
# Generated by setup_audio_sharing.sh on $(date)
#
# PulseAudio is the sole consumer of the ALSA loopback capture device.
# Both the dog bark detector and BirdNET read from PulseAudio.

# Load system defaults
.include /etc/pulse/default.pa

# Load the ALSA loopback capture device as a PulseAudio source
load-module module-alsa-source device=hw:${LOOPBACK_CARD},1 source_name=iphone_audio source_properties=device.description="iPhone_Microphone" rate=16000 channels=1

# Make it the default source
set-default-source iphone_audio
PAEOF

chown "${AUDIO_USER}:${AUDIO_USER}" "$PULSE_DEFAULT"
chown "${AUDIO_USER}:${AUDIO_USER}" "$PULSE_CONFIG"

echo -e "${GREEN}  PulseAudio config written: ${PULSE_DEFAULT}${NC}"

###############################################################################
# Step 3: Ensure UFW allows iPhone UDP (RTP audio packets)
###############################################################################

echo -e "${YELLOW}Step 3: Checking firewall...${NC}"

IPHONE_IP=$(systemctl cat iphone-audio-stream 2>/dev/null | grep -oP 'rtsp://\K[0-9.]+' | head -1 || echo "")

if [ -n "$IPHONE_IP" ]; then
    if ! ufw status 2>/dev/null | grep -q "$IPHONE_IP.*udp.*ALLOW"; then
        ufw allow from "$IPHONE_IP" proto udp comment "iPhone RTP audio stream" 2>/dev/null || true
        echo -e "${GREEN}  Added UFW rule for iPhone UDP ($IPHONE_IP)${NC}"
    else
        echo -e "${GREEN}  UFW already allows UDP from $IPHONE_IP${NC}"
    fi
else
    echo -e "${YELLOW}  Could not detect iPhone IP - check UFW manually${NC}"
fi

###############################################################################
# Step 4: Restart PulseAudio
###############################################################################

echo -e "${YELLOW}Step 4: Restarting PulseAudio...${NC}"

# Kill existing PulseAudio (it auto-respawns)
if sudo -u "$AUDIO_USER" pulseaudio --check 2>/dev/null; then
    sudo -u "$AUDIO_USER" pulseaudio --kill 2>/dev/null || true
    sleep 2
fi

# Start PulseAudio
sudo -u "$AUDIO_USER" pulseaudio --start 2>/dev/null || true
sleep 2

# Verify the source exists
if sudo -u "$AUDIO_USER" pactl list sources short 2>/dev/null | grep -q "iphone_audio"; then
    echo -e "${GREEN}  PulseAudio source 'iphone_audio' is available${NC}"
else
    echo -e "${YELLOW}  PulseAudio source not immediately visible - may need service restart${NC}"
fi

###############################################################################
# Step 5: Verify Audio Flow
###############################################################################

echo -e "${YELLOW}Step 5: Testing audio...${NC}"

TESTFILE="/tmp/pulse_test.wav"
# Record 2 seconds from PulseAudio default source
timeout 4 parecord --rate=16000 --channels=1 --format=s16le --file-format=wav "$TESTFILE" 2>/dev/null &
RECPID=$!
sleep 3
kill $RECPID 2>/dev/null; wait $RECPID 2>/dev/null

if [ -f "$TESTFILE" ] && [ -s "$TESTFILE" ]; then
    LEVEL=$(python3 -c "
import wave, struct
try:
    w = wave.open('${TESTFILE}', 'r')
    frames = w.readframes(w.getnframes())
    if len(frames) < 4:
        print('empty')
    else:
        samples = [abs(struct.unpack('<h', frames[i:i+2])[0]) for i in range(0, min(len(frames), 64000), 2)]
        peak = max(samples)
        if peak < 10:
            print('silence')
        else:
            print(f'ok peak={peak}')
except Exception as e:
    print(f'error: {e}')
" 2>/dev/null)

    case "$LEVEL" in
        ok*)
            echo -e "${GREEN}  Audio is flowing! (${LEVEL})${NC}"
            ;;
        silence)
            echo -e "${YELLOW}  Connected but silent - check iphone-audio-stream service${NC}"
            ;;
        *)
            echo -e "${YELLOW}  Could not verify audio (${LEVEL})${NC}"
            ;;
    esac
    rm -f "$TESTFILE"
else
    echo -e "${YELLOW}  Could not record - PulseAudio may need a moment${NC}"
fi

###############################################################################
# Summary
###############################################################################

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "Architecture:"
echo "  iPhone --> RTSP --> ffmpeg --> hw:${LOOPBACK_CARD},0 (loopback)"
echo "                                     |"
echo "                                hw:${LOOPBACK_CARD},1 (capture)"
echo "                                     |"
echo "                               PulseAudio"
echo "                                /        \\"
echo "                         Bark Detector  BirdNET"
echo ""
echo "Next steps:"
echo "  1. Restart services:"
echo "     sudo systemctl restart iphone-audio-stream"
echo "     sudo systemctl restart dog_bark_detector"
echo ""
echo "  2. Verify audio:"
echo "     sudo journalctl -u dog_bark_detector -n 10 --no-pager"
echo ""
